OCEAN_WIDTH = 30
OCEAN_HEIGHT = 30

MAX_SHARK_ENERGY = 500
MIN_SHARK_MOVE_ENERGY = 20
MIN_SHARK_REPRODUCE_ENERGY = 40
SHARK_REPRODUCTION_PROBABILITY = 0.02
SHARK_CREATION_PROBABILITY = 0.05
MAX_SHARK_AGE = 100

MAX_SARDINE_ENERGY = 30
MIN_SARDINE_MOVE_ENERGY = 1
MIN_SARDINE_REPRODUCE_ENERGY = 5
SARDINE_REPRODUCTION_PROBABILITY = 0.2
SARDINE_CREATION_PROBABILITY = 0.1
MAX_SARDINE_AGE = 30

MAX_PLANKTON_ENERGY = 5
PLANKTON_REPRODUCTION_PROBABILITY = 0.07
PLANKTON_CREATION_PROBABILITY = 0.2
MAX_PLANKTON_AGE = 20


