OCEAN_WIDTH = 150
OCEAN_HEIGHT = 25

MAX_SHARK_ENERGY = 500
MIN_SHARK_MOVE_ENERGY = 20
MIN_SHARK_REPRODUCE_ENERGY = 40
SHARK_REPRODUCTION_PROBABILITY = 0.1
SHARK_CREATION_PROBABILITY = 0.03
MAX_SHARK_AGE = 100

MAX_SARDINE_ENERGY = 30
MIN_SARDINE_MOVE_ENERGY = 1
MIN_SARDINE_REPRODUCE_ENERGY = 5
SARDINE_REPRODUCTION_PROBABILITY = 0.3
SARDINE_CREATION_PROBABILITY = 0.07

MAX_PLANKTON_ENERGY = 5
PLANKTON_REPRODUCTION_PROBABILITY = 0.5
PLANKTON_CREATION_PROBABILITY = 0.2


