OCEAN_WIDTH = 50
OCEAN_HEIGHT = 50

MAX_SHARK_ENERGY = 100000
MIN_SHARK_MOVE_ENERGY = 20
MIN_SHARK_REPRODUCE_ENERGY = 40
SHARK_REPRODUCTION_PROBABILITY = 0.1
SHARK_CREATION_PROBABILITY = 0.03
MAX_SHARK_AGE = 100

MAX_SARDINE_ENERGY = 30
MIN_SARDINE_MOVE_ENERGY = 1
MIN_SARDINE_REPRODUCE_ENERGY = 5
SARDINE_CREATION_PROBABILITY = 0.07

